title: Bündnis F5
email: info@okfn.de
description: >-
  Gemeinwohl statt Tech Konzerne in den Mittelpunkt der Digitalpolitik stellen
baseurl: ""
url: ""

collections:
  publikationen:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-feed

feed:
  collections:
    - publikationen

twitter_username:
github_username:
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
